FROM node:18-alpine3.14 as build

WORKDIR /app

ENV REACT_APP_API_URL "http://localhost:5000"
ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json /app/
COPY ./yarn.lock /app/
RUN yarn

COPY . /app
RUN yarn build


FROM nginx:1.21.6-alpine

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]